version: '3.7'

services:
  react:
    build: .
    ports:
      - "4000:4000"
    volumes:
       - react-home:/react
    networks:
      - shared-net

volumes:
  react-home:

networks:
  shared-net:
    driver: bridge